### ISSUE TITLE
SSL doesn't work anymore

### ISSUE THREAD

**Issue by varna9000** [popnotsoda95/async_urequests#2]
Trying on ESP8266 with MicroPython v1.16

Trying GET on various APIs with SSL returns the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 33, in <module>
  File "uasyncio/core.py", line 1, in run
  File "uasyncio/core.py", line 1, in run_until_complete
  File "uasyncio/core.py", line 1, in run_until_complete
  File "<stdin>", line 27, in show
  File "<stdin>", line 21, in coin_info
  File "async_urequests.py", line 244, in get
  File "uasyncio/funcs.py", line 1, in wait_for
  File "uasyncio/funcs.py", line 1, in runner
  File "uasyncio/core.py", line 1, in run_until_complete
  File "async_urequests.py", line 233, in _requests
ConnectionError: [Errno 11] EAGAIN
```

HTTP works fine.

**Comment by LarsKumbier** [comment]
still broken on v1.18.0
